services:
  data-ingestion:
    container_name: data-ingestion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=${KAFKA_PORT}
      - KAFKA_TOPIC=network.data.ingested
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
      - HOST=data-ingestion
      - PORT=7000
      - PRODUCER_MAX_TIMEOUT=30
    networks:
      - nwdaf-network

networks:
  nwdaf-network:
    external: true
